/**
 * Property-Based Test for S3 Agent Assets - SHA-256 Correctness and
 * Stability
 *
 * Feature: agent-asset-tools
 * Property 9: SHA-256 correctness and stability
 *
 * For any object byte content, the returned `sha256` equals the lowercase
 * hexadecimal SHA-256 digest of those exact bytes computed independently,
 * and repeated reads of unchanged bytes yield an identical `sha256`.
 *
 * **Validates: Requirements 2.3, 3.4**
 *
 * Property test A exercises the pure `computeSha256(buffer)` helper
 * directly: for any generated byte buffer, its output must equal an
 * independently-computed `crypto.createHash('sha256')` digest over those
 * same exact bytes (Requirement 2.3), and that output must be a lowercase,
 * 64-character hexadecimal string.
 *
 * Property test B exercises `get(connection, options)` end-to-end with
 * mocked S3: calling `get()` twice in a row for the identical asset - with
 * `Body.transformToByteArray()` resolving to the SAME mocked bytes on each
 * read - must return an identical `sha256` value both times, and that value
 * must equal the independently-computed SHA-256 of the mocked bytes
 * (Requirement 3.4: "an identical sha256 value on each call, so that the
 * identifier is a stable basis for comparison").
 *
 * S3 is mocked (no live AWS): `@63klabs/cache-data`'s `AWS.s3.client.send`
 * is stubbed following the same pattern used by the sibling
 * `tests/unit/models/s3-agent-assets-dao.test.js` and
 * `tests/unit/models/s3-agent-assets-list-item.property.test.js`.
 */

const crypto = require('crypto');
const fc = require('fast-check');

const mockS3Send = jest.fn();
jest.mock('@63klabs/cache-data', () => ({
  tools: {
    DebugAndLog: {
      debug: jest.fn(),
      info: jest.fn(),
      warn: jest.fn(),
      error: jest.fn()
    },
    AWS: {
      s3: {
        client: {
          send: mockS3Send
        }
      }
    }
  }
}));

jest.mock('../../../utils/error-handler', () => ({
  logS3Error: jest.fn()
}));

// Import after mocking so the DAO (and the s3-common helper it depends on)
// picks up the mocked AWS.s3.client
const S3AgentAssets = require('../../../models/s3-agent-assets');

/** Registry-shaped `steering` type fixture, mirroring config/agent-asset-types.js */
const STEERING_TYPE = { name: 'steering', folder: 'steering', extensions: ['.md'] };
const BASE_PATH = 'utilities/v2/agent_assets';

/** Arbitrary S3 bucket name: lowercase alphanumeric, 3-40 characters. */
const bucketArb = fc.string({
  unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'.split('')),
  minLength: 3,
  maxLength: 40
});

/**
 * Arbitrary namespace: lowercase alphanumeric, 1-30 characters - a valid
 * (hyphen-free) subset of the `^[a-z0-9][a-z0-9-]*$` namespace pattern used
 * elsewhere in the codebase.
 */
const namespaceArb = fc.string({
  unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'.split('')),
  minLength: 1,
  maxLength: 30
});

/** Arbitrary filename: an alphanumeric base joined with the `.md` extension. */
const nameArb = fc.string({
  unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'.split('')),
  minLength: 1,
  maxLength: 20
}).map((base) => `${base}.md`);

/** Arbitrary raw object byte content: any byte array, including empty. */
const bytesArb = fc.uint8Array({ minLength: 0, maxLength: 2000 });

describe('Feature: agent-asset-tools, Property 9: SHA-256 correctness and stability', () => {

  beforeEach(() => {
    mockS3Send.mockReset();
    jest.clearAllMocks();
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  /* ---------------------------------------------------------------- */
  /*  Property test A: computeSha256(buffer) correctness              */
  /*  (Requirement 2.3)                                                */
  /* ---------------------------------------------------------------- */

  describe('computeSha256() correctness against an independent crypto digest', () => {

    /**
     * **Validates: Requirement 2.3**
     *
     * For any generated byte buffer, `computeSha256(buffer)` equals a
     * SHA-256 digest computed independently in the test (a fresh
     * `crypto.createHash('sha256')` call over the same exact bytes, not a
     * second invocation of `computeSha256` itself), and the result is
     * always a lowercase, 64-character hexadecimal string.
     */
    test('computeSha256(buffer) equals an independently computed crypto SHA-256 digest and is lowercase 64-character hex', () => {
      fc.assert(
        fc.property(bytesArb, (bytes) => {
          const buffer = Buffer.from(bytes);

          const actual = S3AgentAssets.computeSha256(buffer);

          // Independent computation performed directly in the test, over
          // the same exact bytes, rather than by re-invoking computeSha256.
          const expected = crypto.createHash('sha256').update(buffer).digest('hex');

          expect(actual).toBe(expected);
          expect(actual).toMatch(/^[0-9a-f]{64}$/);
        }),
        { numRuns: 100 }
      );
    });
  });

  /* ---------------------------------------------------------------- */
  /*  Property test B: get() end-to-end stability across repeated     */
  /*  reads (Requirement 3.4)                                          */
  /* ---------------------------------------------------------------- */

  describe('get() end-to-end sha256 stability across repeated reads of unchanged mocked bytes', () => {

    /**
     * **Validates: Requirements 2.3, 3.4**
     *
     * For any generated bucket/namespace/name and byte payload, mocking S3
     * so that `Body.transformToByteArray()` resolves with the SAME bytes on
     * every `GetObjectCommand`, calling `get()` twice in a row for the
     * identical `connection`/`options` returns the SAME `sha256` value on
     * both calls, and that value equals the SHA-256 computed independently
     * over the mocked bytes.
     */
    test('get() returns an identical sha256 on repeated reads, equal to the independently computed digest of the mocked bytes', () => {
      return fc.assert(
        fc.asyncProperty(
          bucketArb,
          namespaceArb,
          nameArb,
          bytesArb,
          async (bucket, namespace, name, bytes) => {
            mockS3Send.mockReset();

            const expectedBuffer = Buffer.from(bytes);
            const expectedSha256 = crypto.createHash('sha256').update(expectedBuffer).digest('hex');

            // Namespace is supplied directly, so each get() call issues
            // exactly one GetObjectCommand (no namespace-discovery call).
            // mockResolvedValue (not *Once) keeps the SAME mocked payload
            // available across both of the two get() calls below, so a
            // repeated read of "unchanged bytes" is faithfully simulated.
            mockS3Send.mockResolvedValue({
              Body: { transformToByteArray: async () => bytes },
              ETag: '"stable-etag"',
              LastModified: new Date('2024-01-01T00:00:00.000Z')
            });

            const connection = {
              host: bucket,
              path: BASE_PATH,
              parameters: {
                assetType: STEERING_TYPE,
                name,
                namespace
              }
            };

            const first = await S3AgentAssets.get(connection, {});
            const second = await S3AgentAssets.get(connection, {});

            expect(first).not.toBeNull();
            expect(second).not.toBeNull();

            // Stability: repeated reads of unchanged bytes yield an
            // identical sha256 value on each call (Requirement 3.4).
            expect(second.sha256).toBe(first.sha256);

            // Correctness: that stable value equals the SHA-256 computed
            // independently over the exact mocked bytes (Requirement 2.3).
            expect(first.sha256).toBe(expectedSha256);
            expect(second.sha256).toBe(expectedSha256);

            // Exactly one S3 call per get() invocation (namespace supplied
            // directly => no namespace-discovery call), so two get() calls
            // issue exactly two GetObjectCommand calls in total.
            expect(mockS3Send).toHaveBeenCalledTimes(2);
          }
        ),
        { numRuns: 100 }
      );
    });
  });
});
